version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      MONGO_INITDB_DATABASE: social_media_osint_db
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

#  django:
#    build: .
#    container_name: social-net-osint
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongodb
local
are u saying host it on the cloud
it saves data to the databse